package com.studentscouch.projectbostonfiles.miscellaneous_files;

public class GeneralToDos {

    // TODOS ON PRIORITY LEVEL 1: ESSENTIAL TO PROPER BUSINESS/PLATFORM FUNCTIONING

    //TODO: PRIORITY LEVEL 1: ADD PRIVACY STATEMENT

    //TODO: PRIORITY LEVEL 1: FINISH FIREBASE SETUP OF CHAT SDK WHEN FIREBASE PLAN UPGRADED, GEBRUIK OOK APP CHECK FUNCTIE IN FIREBASE CONSOLE OM DDOS AANVALLEN TE VOORKOMEN

    //TODO: PRIORITY LEVEL 1: FINISH SETUP OF STRIPE IMPLEMENTATION WHEN COMPANY INCORPORATED

    // TODOS ON PRIORITY LEVEL 2: VERY IMPORTANT BUT BUT NOT ESSENTIAL TO PROPER BUSINESS/PLATFORM FUCNTIONING

    //TODO: PRIOIRITY LEVEL 2: ADD GOOGLE AND FACEBOOK AUTOMATIC LOG-IN AND ACCOUNT CREATION


}
